name: Build Boost
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libfftw3-dev libtbb-dev perl \
          libboost-system-dev libboost-filesystem-dev libboost-dev libboost-test-dev

    - name: Build and run test script
      run: |
        cd ..
        mkdir TEST
        cd TEST
        export BOOST_ROOT=/usr
        ../seismic-forward/run_cmake.sh || exit 1
        make -j 8 || exit 1
        make test_seismicforward || exit 1
        ../seismic-forward/TestScript.pl || exit 1
